<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery-2.2.0.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/owl.carousel.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/counterup.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/waypoints.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.themepunch.revolution.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.isotope.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.magnific-popup.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.sticky-kit.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.twentytwenty.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.event.move.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.photogrid.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.tooltips.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.pricefilter.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.stacktable.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.contact-form.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/jquery.jpanelmenu.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/headroom.min.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/modernizr.custom.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/puregrid.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/flexibility.js"></script>
<script type="text/javascript" src="<?php dirname(__DIR__) ?>/scripts/custom.js"></script>